### PR TITLE
Allow arbitrary rooms

### PR DESCRIPTION
**Pull request by wendi-yu**
Uses a query string to allow arbitrary rooms. This is probably more suited to Minerva being able to plop in arbitrary rooms since query strings are finicky and not very user-friendly, but hey it works :^) 

Both pages still take default values (`bay_area` and `bay_area2`) without the query string and it seems to work locally on Chrome, Edge, and Firefox.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/meet.website/1)

### CODE REVIEW

**Comment by BluCodeGH** [comment]
That `window.location` stuff is smart, I think we might be able to get arbitrary room names as standard paths by (ab)using the magic `404.html` which gets served for all urls [(example, see 404.html)](https://github.com/rafgraph/spa-github-pages).

I think we should also prepend `bay_area` to all the room names for uniqueness, which would also then let us use just `404.html` for everything (possibly with an exception for `index.html`). Lastly we should pretty-ify the room name to override the room subject as well.

**Comment by wendi-yu** [comment]
I did the room description prettify (overrideable with a specified query string value), and modified the 404 a little since we're not using an SPA. It just directly extracts the broken path and redirects it to a url with the path transformed to a query string, so something like
`https://meet.waterloorocketry.com/bay_area/discuss-the-bay` becomes
`https://meet.waterloorocketry.com/?room=bay_area&desc=discuss-the-bay`.

It doesn't test very well locally since there isn't the magic 404 page, but you can mimic server function to some extent if you go py -m http.server and visit the port it's serving on, 8000 by default.

I think it seems more intuitive to just have people add in `bay_area2` as the path rather than prepending it for them? Do we need uniqueness for this to work?

**Comment by BluCodeGH** [comment]
I suppose uniqueness isn't super important, although I do really like the idea of https://meet.waterloorocketry.com/2 which is easy to map to `bay_area2` with the global prefix.
What if we, instead of redirecting from the `404.html`, served the iframe from it directly? I'm thinking it would be pretty much a copy of `index.html` but instead of using query strings you pull from `window.location` like you're doing already. That means then the URL doesn't need to change which would look pretty snazzy imo.

**Comment by wendi-yu** [comment]
Cool beans I did the thing, it serves directly from the 404 page now. I also changed `index.html` and added a `2.html` so that they both redirect to bay_area and bay_area2, respectively

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks great, just a few nits!

> Reviewed 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/meet.website/1#-:-MUkCX3CCtvG7GnhKlQG:b-jejb7o)* status: all files reviewed, 3 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[404.html, line 12 at r3](https://reviewable.io/reviews/waterloo-rocketry/meet.website/1#-MUkBuUHEfgiF77Z8lg8:-MUkBuUHEfgiF77Z8lg9:b-c0ym3m) ([raw file](https://github.com/waterloo-rocketry/meet.website/blob/7c03ff1c506187501164aedd2b947d1e8d8aa8a0/404.html#L12)):*
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> ```
>       // Single Page Apps for GitHub Pages
>       // MIT License
>       // https://github.com/rafgraph/spa-github-pages
>       // This script takes the current url and converts the path and query
>       // string into just a query string, and then redirects the browser
>       // to the new url with only a query string and hash fragment,
>       // e.g. https://www.foo.tld/one/two?a=b&c=d#qwe, becomes
>       // https://www.foo.tld/?/one/two&a=b~and~c=d#qwe
>       // Note: this 404.html file must be at least 512 bytes for it to work
>       // with Internet Explorer (it is currently > 512 bytes)
>       // If you're creating a Project Pages site and NOT using a custom domain,
>       // then set pathSegmentsToKeep to 1 (enterprise users may need to set it to > 1).
>       // This way the code will only replace the route part of the path, and not
>       // the real directory in which the app resides, for example:
>       // https://username.github.io/repo-name/one/two?a=b&c=d#qwe becomes
>       // https://username.github.io/repo-name/?/one/two&a=b~and~c=d#qwe
>       // Otherwise, leave pathSegmentsToKeep as 0.
> ```
</details>

This isn't correct anymore.
___
*[404.html, line 33 at r3](https://reviewable.io/reviews/waterloo-rocketry/meet.website/1#-MUkCDy0A3PWdpDq-EOG:-MUkCDy0A3PWdpDq-EOH:bnbmmao) ([raw file](https://github.com/waterloo-rocketry/meet.website/blob/7c03ff1c506187501164aedd2b947d1e8d8aa8a0/404.html#L33)):*
> ```
>       const host = l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
>         l.pathname.split('/').slice(0, 1).join('/');
> ```
Unused.
___
*[404.html, line 35 at r3](https://reviewable.io/reviews/waterloo-rocketry/meet.website/1#-MUkCIiR1s9fBfEiclLh:-MUkCIiR1s9fBfEiclLi:b-crnpti) ([raw file](https://github.com/waterloo-rocketry/meet.website/blob/7c03ff1c506187501164aedd2b947d1e8d8aa8a0/404.html#L35)):*
> ```HTML
>         l.pathname.split('/').slice(0, 1).join('/');
>     
>       const paths = l.pathname.slice(1).split('/').map(path => path.replace(/&/g, '~and~'));
> ```

The `.map` call isn't necessary anymore since we don't need to worry about query parameters.

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/meet.website/1#-:-MUkE2124HPZjQ1lzNM4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jacobdeery)

**Pull request merged**
